### ISSUE TITLE
Breaks on NodeJS v14+

### ISSUE THREAD

**Issue by Meizikyn** [lenneTech/cli-starter#13]
```
var/src/fs via ⬢ v14.16.0 took 1m 0s
➜ lt cli create myproject
Create a new CLI
/home/shor/.config/yarn/global/node_modules/gluegun/build/index.js:13
    throw up;
    ^

TypeError: Cannot read property 'getInput' of undefined
    at /home/shor/.config/yarn/global/node_modules/@lenne.tech/cli/build/commands/cli/create.js:30:35
    at Generator.next (<anonymous>)
    at fulfilled (/home/shor/.config/yarn/global/node_modules/@lenne.tech/cli/build/commands/cli/create.js:5:58)
```

Using NodeJS v14.16.0 & v16.2.0, `lt cli create ${projectName}` produces the above error.

Before diving into debugging, is NodeJS beyond v12 intended to be supported?

**Comment by kaihaase** [comment]
@Meizikyn thank you for your request. Our goal is to support at least the latest LTS of NodeJS. I just tried the `lt cli create myproject` command and everything seems to work:

```
lt cli create myproject
Create a new CLI
✔ Enter Author · Kai Haase
✔ Link when finished? (y/N) · false
✔ Repository cloned from https://github.com/lenneTech/cli-starter.git
✔ NPM packages installed
✔ Files & data renamed
✔ Git initialized

Generated myproject server with lenne.Tech CLI 0.0.58 in 0:23m.
```

My MacBook with M1 running MacOS Big Sur (11.4) is currently running NodeJS version 14.16.1 with npm version 7.16.0 (also tried it successfully with npm version 6.14.11). The lt CLI is running in the current version 0.0.58.

Which lt CLI version are you using?
```
lt -v
0.0.58
```
